// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwiv-lHUjRRxnUkxx8RGwWWFiYNt8CsxA',
    appId: '1:745172941537:web:96bbd66f1ab653cfa7d5a0',
    messagingSenderId: '745172941537',
    projectId: 'ecommerce-89969',
    authDomain: 'ecommerce-89969.firebaseapp.com',
    storageBucket: 'ecommerce-89969.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOAdZnCmtMqj8KHpp2F9Y69Ljq0rknneM',
    appId: '1:745172941537:android:dc9e743af251d891a7d5a0',
    messagingSenderId: '745172941537',
    projectId: 'ecommerce-89969',
    storageBucket: 'ecommerce-89969.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs7M0DpGQI0ZTqII2w5KHzElhMdRJXGJY',
    appId: '1:745172941537:ios:81c448e3cf47c6fca7d5a0',
    messagingSenderId: '745172941537',
    projectId: 'ecommerce-89969',
    storageBucket: 'ecommerce-89969.appspot.com',
    iosClientId: '745172941537-kg464l6a9kmsbu003l5477pqoehrmnfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs7M0DpGQI0ZTqII2w5KHzElhMdRJXGJY',
    appId: '1:745172941537:ios:c01969853a6448ffa7d5a0',
    messagingSenderId: '745172941537',
    projectId: 'ecommerce-89969',
    storageBucket: 'ecommerce-89969.appspot.com',
    iosClientId: '745172941537-a4sa994vq9lr44if74hkuon5s6vb2tie.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomm.RunnerTests',
  );
}
